### ISSUE TITLE
Show highest ranking article on click in main line chart 

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#16]
When a user clicks on a point in the main line chart, information is shown for that day below the chart:

* [x] Date
* [ ] epu-index
* [x] Highest ranking article title
* [x] Highest ranking article URL
* [x] Highest ranking article newspaper
* [x] The information updates in place on a new click
* [x] The information disappears on brushing (see #28)

**Comment by peterdesmet** [comment]
Is there already data and an API for articles per day?

**Comment by bartaelterman** [comment]
No, should add an issue for @niconoe for that.

**Comment by peterdesmet** [comment]
Blocked by #46

**Comment by peterdesmet** [comment]
When no date is selected and on brushing:

![screen shot 2015-07-27 at 16 43 28](https://cloud.githubusercontent.com/assets/600993/8908875/bffad4a4-347e-11e5-98f6-2e90ea59158a.png)

When no articles are returned for that date:

![screen shot 2015-07-27 at 16 43 18](https://cloud.githubusercontent.com/assets/600993/8908895/d5604fea-347e-11e5-913f-7de7132d187b.png)

When an article is available:

![screen shot 2015-07-27 at 16 43 08](https://cloud.githubusercontent.com/assets/600993/8908948/2992293a-347f-11e5-8a21-09360dbd403e.png)

Note that the link will be black on the production website.

---

I also added some section titles to the viz:

![screen shot 2015-07-27 at 16 43 08](https://cloud.githubusercontent.com/assets/600993/8908909/ec945b98-347e-11e5-9924-eda5013272dd.png)

**Comment by peterdesmet** [comment]
Instead of gray indicator lines, I made them black, for clearer indication on high peaks (compare colour with screenshot above, note: there was no line in the detailed chart there yet). It is the same colour as the hover line though, maybe I should use a dark gray instead? Click screenshot to see the actual design (scaled down the lines appear thicker).

![screen shot 2015-07-27 at 17 10 37](https://cloud.githubusercontent.com/assets/600993/8909611/8f1ee9de-3482-11e5-9683-79767fba6798.png)

**Comment by bartaelterman** [comment]
I like it!

Black lines are fine for me...
