### ISSUE TITLE
Create download form

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#5]
Create a form to download data:

* [x] Start date
* [x] End date
* [ ] `Download data` button
* [ ] Calendar UI elements (optional)

**Comment by peterdesmet** [comment]
Blocked by #45

**Comment by peterdesmet** [comment]
I see two options:

## 1. Download links

![screen shot 2015-07-27 at 17 22 22](https://cloud.githubusercontent.com/assets/600993/8909880/18eacd44-3484-11e5-9f91-33f50d56b5cc.png)

Advantages:

* Good connection with current interface and selection mechanism
* Easy to implement

Disadvantages:

* Even though API supports it, user cannot download a custom range (but can do so offline on all data)

## 2. Download form

A form with two text boxes for start and end date + a download button

Advantages:

* User can select custom range

Disadvantages:

* More complex (i.e. date validation + potentially calendar UI to help user)
* No connection with what user is currently viewing (doesn't feel like it's part of the viz).

OK if I implement option 1?

**Comment by bartaelterman** [comment]
OK

**Comment by peterdesmet** [comment]
Option 1 implemented in 4349c8272cebc0282a4709555d0cd3dc5c0aa2a6, using d3 to update the `href` attribute of the download link on a new selection (so no `on("click")` event required).

I also subtracted one day from the year range, so instead of the previous 2010-09-01 to 2011-09-01, it now shows 2010-09-01 to 2011-08-31. This is more what the user expects (e.g. title shows sep-aug, instead of sep-sep and only unique dates are listed in the download): a30cf1d52fba3dc6bbfbec300b7e5bc022efbc34
