### ISSUE TITLE
Deploy web app

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#58]
- [x] Set up an account on a cloud service
- [x] Install Django and other requirements
- [x] Clone git repo
- [x] Download data files
- [x] Set up database
- [x] Configure Django app and Scrapy project
- [x] Migrate data
- [x] Start Django app
- [ ] Configure periodic Scrapy runs

**Comment by bartaelterman** [comment]
@niconoe feel free to set up an instance somewhere. I can deploy the scrapers, but then I'll need access.

**Comment by niconoe** [comment]
Hi @bartaelterman,

I had a look at this, but since we probably want to avoid to have the DigitalOcean account in our name/VISA card (we would have to re-bill them their usage every month...), I was thinking that maybe the best solution is that they create a DigialOcean account with their billing information, then give us the login/password, so we can create and configure the virtual server for them? Another less intrusive but less technical solution (for them!) would be that they create and configure the VPS and just give us a root SSH access...

There's also apparently an option to create a snapshot of a server and to move it to another customer, but overall it doesn't seem easier (they still need to create an account, the correct configuration, ...).

What do you think? 

thanks,

Nicolas

**Comment by bartaelterman** [comment]
Agreed. I will do that together with them then. In that case, we can delay this issue until then.
